export const PERMISSION = {
  ACTIVE_USERS: "ACTIVE_USERS",
  READ_USERS: "READ_USERS",
  ALL: "ALL",
  EXECUTE_NOVELS: "EXECUTE_NOVELS",
  WRITE_NOVELS: "WRITE_NOVELS",
  READ_NOVELS: "READ_NOVELS",
};
